version: 2.0 
phases:
  install:
    commands:
      - echo install serverless
      - npm i -g serverless
  pre_build:
    commands:
      - echo install npm packages
      - npm install
  build:
    commands:
      - echo deployment started at `date`
      - echo Deploying with serverless fram
      - sls deploy -v -s $ENV_NAME
  post_build:
    commands:
      - echo deployment completed at `date`